version: '2'
services:

  chucknorris-service:
    image: chucknorris-service
    depends_on:
      - database
    environment:
      - MYSQL_URL=jdbc:mysql://database:3306/chuck?user=chuck&password=norris
      - SERVICE_VERSION=2

  database:
    image: chucknorrisfactsdb
  gateway:
    image: gateway
    links:
      - chucknorris-service
    ports:
      - "8080:8080"
